ppwlabnew/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story7/', include('story7.urls')),
    path('', include('story7.urls')),
]

story7/urls.py
from django.urls import path, re_path
from .views import index, lib, jsonBook, bio, subs, submit, check_email
from .views import post_status
#this is a comment
urlpatterns = [
    path('', bio, name='bio'),
    re_path('test/', post_status, name='post_status'),
    path('books/', lib, name='lib'),
    path('data/', jsonBook, name='data'),
    path('status/', index, name='index'),
    path('subscribe/', subs, name='subscribe'),
    re_path('subscribe/submit', submit, name='submit'),
    re_path('subscribe/checkemail', check_email, name='check_email')
]

story7/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    title = models.CharField(max_length=20)
    status = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Subscribe(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=150)

    def __str__(self):
        return self.name

story7/forms.py
from django import forms
from .models import *

class StatusForm(forms.Form):
    attrs = {
        'class': 'form-control'
    }
    title = forms.CharField(label = 'Title', required = True, widget=forms.TextInput(attrs=attrs), max_length=30)
    status = forms.CharField(label = 'Status', required = True, widget=forms.TextInput(attrs=attrs), max_length=300)

    class Meta:
        model = Status

class SubscriberForm(forms.Form):
    attrs = {
        'class': 'form-control'
    }
    name = forms.CharField(label="Name", required=True, max_length=100, widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(label="Email", required=True, max_length=50, widget=forms.EmailInput(attrs=attrs))
    password = forms.CharField(label="Password", required=True, max_length=150, widget=forms.PasswordInput(attrs=attrs))

    class Meta:
        model = Subscribe

story7/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .forms import StatusForm, SubscriberForm
from .models import Status, Subscribe
import requests
from django.http import JsonResponse
from django.db import IntegrityError
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
response = {}
responseForm = {}

def index(request):
    allstatus = Status.objects.all().order_by('-created_date')
    response['all_status'] = allstatus
    response['status_form'] = StatusForm
    return render(request, "home.html", response)

def post_status(request):
    if request.method == 'POST' and 'submit' in request.POST:
        response['title'] = request.POST['title']
        response['status'] = request.POST['status']
        status_save = Status(title=response['title'], status=response['status'])
        status_save.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

def lib(request):
    return render(request, "lib.html")

def jsonBook(request, pick=''):
    url = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + {pick})
    jsons = url.json()
    return JsonResponse(jsons)

def bio(request):
    return render(request, "bio.html")

def subs(request):
    form = SubscriberForm(request.POST or None)
    responseForm['form'] = form
    return render(request, 'subscribe.html', responseForm)

def submit(request):
    try:
        if (request.method == 'POST'):
            name = request.POST.get('name', None)
            email = request.POST.get('email', None)
            password = request.POST.get('password', None)
            Subscribe(name=name, email=email, password=password).save()
            return HttpResponse(json.dumps({'result': 'Registration is completed'}))
        else:
            return HttpResponse(json.dumps({'result': 'Registration failed, please try again'}))
    except IntegrityError as error:
        return HttpResponse(json.dumps({'result': 'Registration failed, please try again'}))

def check_email(request):
    mail = request.POST.get('email', None)
    data = {
        'already_registered': Subscribe.objects.filter(email=mail).exists()
    }
    return JsonResponse(data)

story7/templates/bio.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
  <style>
  html {
    height: 100%;
    box-sizing: border-box;
  }
  body {
    position: relative;
    margin: 0;
    min-height: 100%;
    padding-bottom: 4rem;
  }
  .footer {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1rem;
    background-color: #f5f5f5;
    color: #73748F;
   }
    #content {
        width: 100%;
        padding: 20px;
        min-height: 100vh;
        transition: all 0.3s;
    }

    .social-icons a {
      display: inline-block;
      height: 3.5rem;
      width: 3.5rem;
      background-color: #4BB7F4;
      color: #fff !important;
      border-radius: 100%;
      text-align: center;
      font-size: 1.5rem;
      line-height: 3.0rem;
      margin-right: 1rem;
    }

    .social-icons a:last-child {
      margin-right: 0;
    }

    .social-icons a:hover {
      background-color: #6d7fcc;
    }

    .square {
        height: 220px;
        width: 220px;
        margin-right: 30px;
        margin-bottom: 15px;
        overflow: hidden;
    }
  .navbar {
	background-color: #f5f5f5;
    color: #73748F;
   }
  </style>

    <meta charset="utf-8" />
    <title>Hello there (General Kenobi)!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand nav-link" href="{% url 'bio' %}">Ihsan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'bio' %}">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'index' %}">Status</a>
                <a class="nav-item nav-link" href="{% url 'lib' %}">Books</a>
                <a class="nav-item nav-link" href="{% url 'subscribe' %}">Subscribe</a>
            </div>
        </div>
    </nav>

  <body>
    <div class="container">
        <div id="content">
			  <section class="resume-section p-3 p-lg-5 d-flex d-column">
				<div class="my-auto">
					<div class="img-fluid float-left">
						<div class="square"><img class="img-fluid img-profile rounded-circle" src="https://i.postimg.cc/tJKVprwt/749_AAF23-4_A14-46_D3-_BEA9-_E801_B5711960.png" alt=""></div>
					</div>
				  <h1 class="mb-0">Ihsan
					<span class="text-primary">Muhammad Aulia</span>
				  </h1>
				  <div class="subheading mb-5">Jl. Bambu Kuning Selatan No. 19 · Jakarta Timur, PO BOX 13890 · 08977073540 ·
					<a href="mailto:ihsanmaulia@gmail.com">ihsanmaulia@gmail.com</a>
				  </div>
				  <p class="lead mb-5">I'm a computer science student at University of Indonesia. I usually spend my free time by reading news, especially about tech. I’m a consistent learner, and I love to expand my abilities and experiences by trying something new.</p>
				  <div class="social-icons">
					<a href="https://twitter.com/ihsanauliaa">
					  <img src= https://i.postimg.cc/J4cMx6Kw/twitter-logo-silhouette_1.png width="32" height="32"></img>
					</a>
					<a href="https://www.linkedin.com/in/ihsan-ma-175a64153/">
					  <img src= https://i.postimg.cc/SN57ZdKr/linkedin.png width="32" height="32"></img>
					</a>
					<a href="https://gitlab.com/ihsanaulia">
					  <img src= https://i.postimg.cc/0N3sjL5S/git-logo.png width="32" height="32"></img>
					</a>
				  </div>
				</div>
			  </section>
			</div>
        </div>
    </div>
  </body>

  <footer class = "footer">
	<div class = "container">
		<span class = "text">Ihsan M. Aulia</span>
		<span class = "text">© 2018 Copyright</span>
	</div>
  </footer>


</html>

{% block content %}
{% endblock %}

story7/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
  <style>
  html {
    height: 100%;
    box-sizing: border-box;
  }
  body {
    position: relative;
    margin: 0;
    min-height: 100%;
    padding-bottom: 4rem;
  }
  .footer {
	position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1rem;
	background-color: #f5f5f5;
    color: #73748F;
   }
  .btn-primary.custom-btn1 {
	background-color: #87cefa;
	border-color: #87cefa;
  }
  .btn-primary.custom-btn2 {
	background-color: #D3D3D3;
	border-color: #D3D3D3;
  }
  .btn-primary.custom-btn3 {
	background-color: #f5f5f5;
	border-color: #f5f5f5;
    color: #73748F;
  }
  .accordion-content {
      display: none;
  }
  .se-pre-con {
	position: fixed;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	z-index: 9999;
	background: url(https://mir-s3-cdn-cf.behance.net/project_modules/disp/585d0331234507.564a1d239ac5e.gif) center no-repeat #fff;
  }
  .navbar {
	background-color: #f5f5f5;
    color: #73748F;
   }
  </style>

    <meta charset="utf-8" />
    <title>Write anything!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    <script>
        $(document).ready(function() {
            setTimeout(function(){
                $(".se-pre-con").fadeOut("slow");
            }, 250);
        });
        $(document).ready(function() {
            $("#button-blue").click(function() {
                $(".footer").css("background-color","#87cefa"); //edit, body must be in quotes!
                $(".footer").css("color","#ffffff"); //edit, body must be in quotes!
            });
        });
        $(document).ready(function() {
            $("#button-silver").click(function() {
                $(".footer").css("background-color","#D3D3D3"); //edit, body must be in quotes!
                $(".footer").css("color","#ffffff"); //edit, body must be in quotes!
            });
        });
        $(document).ready(function() {
            $("#button-default").click(function() {
                $(".footer").css("background-color","#f5f5f5"); //edit, body must be in quotes!
                $(".footer").css("color","#73748F"); //edit, body must be in quotes!
            });
        });
        $(document).ready(function($) {
            $('#accordion').find('.card-link').click(function(){

            //Expand or collapse this panel
            $(this).next().slideToggle('fast');

            //Hide the other panels
            $(".accordion-content").not($(this).next()).slideUp('fast');

            });
        });
    </script>
  </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand nav-link" href="{% url 'bio' %}">Ihsan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'bio' %}">Home</a>
                <a class="nav-item nav-link active" href="{% url 'index' %}">Status<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'lib' %}">Books</a>
                <a class="nav-item nav-link" href="{% url 'subscribe' %}">Subscribe</a>
            </div>
        </div>
    </nav>

    <body>
    <div class="se-pre-con"></div>
      <div class="container">
          <br>
          <h1>Hello, Apa kabar?</h1>
      </div>

      <div class="container">
          <div id="accordion">
              <div class="card">
                  <div class="card-header">
                      <a class="card-link" data-toggle="collapse" href="#collapseOne">Tentang pembuat website</a>
                          <div class="accordion-content default">
                            <li>I'm a computer science student at University of Indonesia. I usually spend my free time by reading news, especially about tech.</li>
                          </div>
                  </div>
              </div>
              <div class="card">
                  <div class="card-header">
                      <a class="card-link" data-toggle="collapse" href="#collapseTwo">Keseharian pembuat website</a>
                          <div class="accordion-content">
                              <li>First Place - Abacus Competition Intermediate Level (2013 - 2016)</li>
                              <li>2006 Times Magazine Person of The Year (Seriously, look it up)</li>
                          </div>
                  </div>
              </div>
              <div class="card">
                  <div class="card-header">
                      <a class="card-link" data-toggle="collapse" href="#collapseThree">Pengalaman pembuat website</a>
                          <div class="accordion-content">
                            <li>DPM UI Internship Project Officer (2018)</li>
                            <li>DPM UI Staff (2018 - 2019)</li>
                            <li>Freedom of 48 Logistical Staff (2015)</li>
                            <li>Junior High School Student Council Staff (2012 - 2013)</li>
                          </div>
                  </div>
              </div>
          </div>
      </div>

      <br>

      <div class="container">
          <button type="button" id="button-blue" class="btn btn-primary custom-btn1">Slight Blue</button>
          <button type="button" id="button-silver" class="btn btn-primary custom-btn2">Very Silver</button>
          <button type="button" id="button-default" class="btn btn-primary custom-btn3">Default</button>
      </div>

      <br>

      <div class="container">
          <div class= "form-group">
                <form id="form" method="POST" action="{% url 'post_status' %}">
                {% csrf_token %}
                {{status_form}}
                <br><button type="submit" name="submit" class="btn btn-lg btn-block btn-info">Submit</button>
          </div>
      </div>

      <div class="container">
          <div>
            {% for i in all_status %}
                <h3>{{i.title}}</h3>
                <p>{{i.status}}</p>
            {% endfor %}
          </div>

      </div>
  </body>

  <footer class = "footer">
	<div class = "container">
		<span class = "text">Ihsan M. Aulia</span>
		<span class = "text">© 2018 Copyright</span>
	</div>
  </footer>


</html>

{% block content %}
{% endblock %}

story7/templates/lib.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
  <style>
  html {
    height: 100%;
    box-sizing: border-box;
  }
  body {
    position: relative;
    margin: 0;
    min-height: 100%;
    padding-bottom: 4rem;
  }
  .footer {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1rem;
    background-color: #f5f5f5;
    color: #73748F;
   }
  img {
       cursor: pointer;
  }
  #custom-search-input{
    padding: 3px;
    border: solid 1px #E4E4E4;
    border-radius: 6px;
    background-color: #fff;
    }

  #custom-search-input input{
    border: 0;
    box-shadow: none;
  }
  .navbar {
	background-color: #f5f5f5;
    color: #73748F;
   }
  </style>

    <meta charset="utf-8" />
    <title>Choose your books!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
        var favorite=0;
        function select(id){
	        var ids= $('#' +id);
	        if (ids[0].src == 'https://i.postimg.cc/SxSXXX0B/unselected.png') {
                favorite++;
                ids[0].src = 'https://i.postimg.cc/TYX567tY/selected.png';
            } else {
                favorite--;
                ids[0].src = 'https://i.postimg.cc/SxSXXX0B/unselected.png';
            }
            $('#counter').html('<br><h1>Your favourite: '+ favorite+ '</h1>');
        }
        function pick(cat) {
	        $('#counter').html('<br><h1>Your favourite: '+ favorite+ '</h1>');
	        $('#books').html("<tr><th id='table'>Cover</th><th id='table'>Title</th><th id='table'>Author</th><th> Fav </th></tr>")
	        $.ajax({
		        url: 'https://www.googleapis.com/books/v1/volumes?q='+cat,
		        success: function(obj){
			        var i;
		            for(i = 0; i <obj.items.length; i++){
			        var title= obj.items[i]['volumeInfo']['title'];
			        var image= '<img src="' + obj.items[i]['volumeInfo']['imageLinks']['thumbnail'] +'">';
			        var author= obj.items[i]['volumeInfo']['authors'];
			        $('#books').append('<tr><td>'+image+'</td><td>'+title+'</td><td>'+ author+'</td><td> <img onclick = select("'+ obj.items[i].id +'") id='+obj.items[i].id+' src="https://i.postimg.cc/SxSXXX0B/unselected.png" style="height:50px;"></td></tr>');
		            }
	        }});
        }
    </script>
  </head>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand nav-link" href="{% url 'bio' %}">Ihsan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'bio' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'index' %}">Status</a>
                <a class="nav-item nav-link active" href="{% url 'lib' %}">Books<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'subscribe' %}">Subscribe</a>
            </div>
        </div>
    </nav>

  <body>
      <div class="container" id="counter">
          <br>
          <h1>Your favourite: 0</h1>
      </div>

      <div class="container">
          <div class="row">
            <div class="col-md-10">
                <h3>Search your book</h3>
                    <div class="input-group mb-3">
                        <input type="text" id="search" value="" class="form-control input-lg" placeholder="Category">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" onclick="pick(search.value)">Search</button>
                        </div>
                    </div>
            	</div>
          </div>
      </div>

      <br>

      <table id='books' class="table container" style="text-align: center; background-color:rgb(255,255,255,0.5)">
			<tr>
                <th id='table'>Cover</th>
                <th id='table'>Title</th>
				<th id='table'>Author</th>
				<th> Favorite </th>
            </tr>
      </table>
  </body>

  <footer class = "footer">
	<div class = "container">
		<span class = "text">Ihsan M. Aulia</span>
		<span class = "text">© 2018 Copyright</span>
	</div>
  </footer>


</html>

{% block content %}
{% endblock %}

story7/templates/subscribe.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
  {% csrf_token %}
  <style>
  html {
    height: 100%;
    box-sizing: border-box;
  }
  body {
    position: relative;
    margin: 0;
    min-height: 100%;
    padding-bottom: 4rem;
  }
  .footer {
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 1rem;
    background-color: #f5f5f5;
    color: #73748F;
   }
  .social-icons a {
      display: inline-block;
      height: 3.5rem;
      width: 3.5rem;
      background-color: #4BB7F4;
      color: #fff !important;
      border-radius: 100%;
      text-align: center;
      font-size: 1.5rem;
      line-height: 3.0rem;
      margin-right: 1rem;
  }

  .social-icons a:last-child {
      margin-right: 0;
  }

  .social-icons a:hover {
      background-color: #6d7fcc;
  }
  .navbar {
	  background-color: #f5f5f5;
      color: #73748F;
   }
   #id_name, #id_email, #id_password{
	  border-color:blue;
   }
  </style>

    <meta charset="utf-8" />
    <title>Hello there (General Kenobi) !</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script>
        var can_submit=false;
        var csrftoken = getCookie('csrftoken');
        function getCookie(c_name)
        {
            if (document.cookie.length > 0)
            {
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1)
                {
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) c_end = document.cookie.length;
                    return unescape(document.cookie.substring(c_start,c_end));
                }
            }
            return "";
         }
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }

        function valid(){
            if(($("#id_email").val()==null || $("#id_email").val()=="") || ($("#id_password").val()==null || $("#id_password").val()=="") || ($("#id_name").val()==null || $("#id_name").val()=="")){
                return false;
            }
            return true;
        }

        $(document).ready(function() {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $("form").submit(function(event) {
                $.ajax({
                    method: "POST",
                    url: '/subscribe/submit/',
                    data: {
                        'name': $('#id_name').val(),
                        'email': $("#id_email").val(),
                        'password': $("#id_password").val(),
                    },
                    dataType: 'json',
                    success: function(msg) {
                        $("#id_password").val('');
                        $("#id_name").val('');
                        $("#id_email").val('');
                        alert("Thank you for registering");
                        $('#warning').html('');

                    },
                    error: function(msg){
                        alert('Email NOT Sent');
                    },
                });
                event.preventDefault();
            });
            $(document).ready(function() {
                $("#submit").click(function() {
                    $('#warning').html('You will be notified for the first newsletter soon');
                });
            });
            $("#id_password").change(function () {
                if (valid() && can_submit){
                    $("#submit")[0].disabled=false;
                }
                else {
                    $("#submit")[0].disabled=true;
                }
            });
            $("#id_name").change(function () {
                if(valid() && can_submit){
                    $("#submit")[0].disabled=false;
                }
                else{
                    $("#submit")[0].disabled=true;
                }
            });
            $("#id_email").change(function () {
                email = $(this).val();
                $.ajax({
                    method: "POST",
                    url: '/subscribe/checkemail/',
                    data: {
                        'email': email
                    },
                    dataType: 'json',
                    success: function (data) {

                        if (isEmail(email)==false) {
                            $('#id_email').css("border-color", "red");
                            $("#submit")[0].disabled=true;
                            $('#warning').html('Email is not valid');
                            can_submit=false;

                        }
                        else if (data.already_registered) {
                            alert("Email is already registered");
                            $('#id_email').css("border-color", "red");
                            $("#submit")[0].disabled=true;
                            $('#warning').html('Email is already registered');
                            can_submit= false;
                        }
                        else {
                            if (valid()){
                                $("#submit")[0].disabled=false;
                                $('#id_email').css("border-color", "blue");
                            }
                            can_submit=true;
                            $('#warning').html('');
                        }
                    }
                });
            });
        })
    </script>
  </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand nav-link" href="{% url 'bio' %}">Ihsan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'bio' %}">Home </a>
                <a class="nav-item nav-link" href="{% url 'index' %}">Status</a>
                <a class="nav-item nav-link" href="{% url 'lib' %}">Books</a>
                <a class="nav-item nav-link active" href="{% url 'subscribe' %}">Subscribe <span class="sr-only">(current)</span></a>
            </div>
        </div>
    </nav>

  <br>

  <body>
    <div class="container">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <p class="label_tag">{{ field.label_tag }} <br> {{ field }} </p>
                {% endfor %}
                <input style="margin-bottom:10px" disabled=true class="btn btn-info btn-lg" id="submit"  type="submit" value="Submit" >
            </form>

        <div id="dialog" title="Announcement"></div>

        <div id="warning"></div>
    </div>

    <div class="container">
        <p class="lead mb-5">Register to get newsletters and more!</p>
    </div>
  </body>

  <footer class = "footer">
	<div class = "container">
		<span class = "text">Ihsan M. Aulia</span>
		<span class = "text">© 2018 Copyright</span>
	</div>
  </footer>


</html>

{% endblock %}